### ISSUE TITLE
Add better documentation for checkpoint

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/checkpoint#129]
- [x] Higher-level introduction docs for how checkpoint serializers work
- [x] Documentation on how virtual serialize works
- [x] Checkpointing vs serialize APIs

@uhetmaniuk Can you create a docs directly here for the markdown? We can add to VT documentation generation the markdown directory so it gets generated. You can take a look in VT in how it's generated with the docs .github workflow. It might also be nice to be able to generate the oxygen separately (not sure if it's work setting that up or not).

@cz4rs Please add comments here for other documentation you would like added.

**Comment by cz4rs** [comment]
ok, some random thoughts from me:
- nice to have: general build instructions (especially for potential outsiders), including optional components (kokkos and detector)
note: build script has `/Users/jliffla/codes/..` hardcoded twice, to be removed
- the `examples` are pretty useful already, a short explanation (comment in the source code?) for each of them would be helpful
- for reference, virtual serialize is currently described here: https://github.com/DARMA-tasking/checkpoint/blob/develop/src/checkpoint/dispatch/dispatch_virtual.h

- related: tutorial section in vt, this can be expanded / moved?
https://github.com/DARMA-tasking/vt/blob/develop/docs/md/tutorial-1c.md (live: https://darma-tasking.github.io/docs/html/tutorial-1c.html)

**Comment by lifflander** [comment]
@cz4rs @uhetmaniuk 

- I agree that a tutorial on checkpoint itself would be useful---a general introduction to how recursive serializers work along with serialization modes.
- @uhetmaniuk You can look at how I include source code from an example in VT in doxygen using the tags in the source code to stop and start an excerpt: https://github.com/DARMA-tasking/vt/blob/ab70256257a2b0beed81e22818fa8780a955a057/examples/hello_world/hello_world_collection_collective.cc#L47-L87 (useful if you want to include code from the checkpoint library in documentation)

Do you guys have opinions on whether checkpoint should include its own doxygen so it can be generated separately? I'm thinking that might be useful in some cases especially by people that only use checkpoint and not all of VT+checkpoint.

**Comment by lifflander** [comment]
@PhilMiller If you have opinions on documentation for checkpoint, please comment on this issue

**Comment by cz4rs** [comment]
> Do you guys have opinions on whether checkpoint should include its own doxygen so it can be generated separately? I'm thinking that might be useful in some cases especially by people that only use checkpoint and not all of VT+checkpoint.

:+1: for this, especially for someone using only checkpoint. You could also make an argument that even for VT development, a self-contained checkpoint documentation is easier to follow.

>  (...) You can look at how I include source code from an example in VT in doxygen using the tags in the source code to stop and start an excerpt (...)

to that point, this example: https://github.com/DARMA-tasking/checkpoint/blob/7c8115e7d63eef9cc8dcaaf8f2c9c5fd31089cae/src/checkpoint/dispatch/dispatch_virtual.h#L84-L101 seems to be broken (I will see if this can be fixed with #127):
```
../src/checkpoint/dispatch/vrt/virtual_serialize.h:95:34: error: no matching function for call to ‘std::allocator<const char>::allocator(<brace-enclosed initializer list>)’
   95 |     auto t = std::allocator<T>{}.allocate(1);
      |                   ~~~~~~~~~~~~~~~^~~~~~~~
```

**Comment by uhetmaniuk** [comment]
@lifflander @PhilMiller @cz4rs 
I am not sure how to explain / document the compile-time failure of `TestShouldFailReconstruct` in `examples/checkpoint_example_3.cc`
I feel like my understanding of `checkpoint` is not complete here.

**Comment by lifflander** [comment]
> @lifflander @PhilMiller @cz4rs
> I am not sure how to explain / document the compile-time failure of `TestShouldFailReconstruct` in `examples/checkpoint_example_3.cc`
> I feel like my understanding of `checkpoint` is not complete here.

I'll take a look at it and add some explanation.

**Comment by lifflander** [comment]
`TestShouldFailReconstruct` has an explicitly deleted default constructor and a constructor that takes an `int` parameter. Thus, serialization has no way to construct the class:
```C++
struct TestShouldFailReconstruct {
  int a = 29;

  TestShouldFailReconstruct(int const) { }
  TestShouldFailReconstruct() = delete;

  template <typename Serializer>
  void serialize(Serializer& s) {
    s | a;
  }
};
```

If you compare this to `TestReconstruct`, it has the same deleted default constructor, but it contains a static reconstructor method that serialization can use to construct the class. An alternative to this would be a tagged constructor (or a constructor that takes`SERIALIZE_CONSTRUCT_TAG`).

```C++
  static TestReconstruct& reconstruct(void* buf) {
    auto a = new (buf) TestReconstruct(100);
    return *a;
  }
```

For a class to be serializable, it must have a valid reconstruction method.

**Comment by uhetmaniuk** [comment]
@lifflander 
I am not familiar with using Docker inside GitHub actions.
So I have tried to build a plain action and generated a dummy webpage 

https://uhetmaniuk.github.io/test-doc/build/docs/html/

One difference with the Docker approach is that the website is stored in a branch of repository.
Please let me know whether you prefer the Docker approach.

**Comment by lifflander** [comment]
> @lifflander
> I am not familiar with using Docker inside GitHub actions.
> So I have tried to build a plain action and generated a dummy webpage
> 
> https://uhetmaniuk.github.io/test-doc/build/docs/html/
> 
> One difference with the Docker approach is that the website is stored in a branch of repository.
> Please let me know whether you prefer the Docker approach.

@uhetmaniuk I do prefer running these in a Docker container. If we create a separate repository for the website that is probably ideal for committing the website pages when a merge on develop happens.

I can walk you through the Docker setup and building a container if you want. What questions do you have about it?

**Comment by uhetmaniuk** [comment]
@lifflander

I copied the following files from VT: ``.github/workflows/build-docs.yml``, ``docker-compose.yml``, ``ci/build_cpp.sh``, ``ci/docker/ubuntu-18.04-gnu-docs.dockerfile`` and adapted them to use variables or references about checkpoint.

When I run the action ``build-docs.yml``, I get the following error
```
No such file or directory: '/build/checkpoint/Doxyfile-mcss' 
```

even though I created a ``Doxyfile.in-mcss``. 

- I can not find the difference between this approach and the version for VT. Could you remind me which command generates the files `Doxyfile` and `Doxyfile-mcss` ?
- In ``ci/build_cpp.sh``, the (VT-related) webpages are pushed on the repository ```DARMA-tasking/DARMA-tasking.github.io```. Where do you want to store the (checkpoint-related) webpages?

**Comment by uhetmaniuk** [comment]
> When I run the action `build-docs.yml`, I get the following error
> 
> ```
> No such file or directory: '/build/checkpoint/Doxyfile-mcss' 
> ```
> 
> even though I created a `Doxyfile.in-mcss`.
> 
> * I can not find the difference between this approach and the version for VT. Could you remind me which command generates the files `Doxyfile` and `Doxyfile-mcss` ?

I fixed that part. I forgot to include ``load_doxygen.cmake`` in ``CMakeLists.txt``

**Comment by uhetmaniuk** [comment]
@lifflander 

In the VT repository, the (VT-related) webpages are pushed on the repository DARMA-tasking/DARMA-tasking.github.io. 
Where do you want to store the (checkpoint-related) webpages?

**Comment by uhetmaniuk** [comment]
m.css gave an AssertionError when `M_SHOW_UNDOCUMENTED` is enabled and the enumeration `eSerializationMode` is defined as `enum struct eSerializationMode : int8_t`.
Removing the name `struct` fixed the error.
But I do not know whether this is a long term fix.

**Comment by lifflander** [comment]
> m.css gave an AssertionError when `M_SHOW_UNDOCUMENTED` is enabled and the enumeration `eSerializationMode` is defined as `enum struct eSerializationMode : int8_t`.
> Removing the name `struct` fixed the error.
> But I do not know whether this is a long term fix.

That surprising to me because be have other `enum struct` enums in the main VT code---quite a few. Could it be something else causing the error?

**Comment by uhetmaniuk** [comment]
I noticed that VT had several `enum struct`.
`doxygen` runs successfully.
When `m-css` runs, it crashes as mentioned.
I agree that there may be another error but I have not been able to find anything else. 
(The rest of the `md` files look similar to the VT files as far as I can tell).
